project:
  type: website
  output-dir: docs

website:
  title: "Statisticats 🐱"
  site-url: https://rodrigozepeda.github.io/Statisticats/
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/RodrigoZepeda/Statisticats
      - icon: twitter
        href: https://twitter.com/RodZepeda
      - icon: rss
        href: index.xml
  margin-header: subscribe.html
format:
  html:
    theme:
      - yeti
      - custom.scss
      
fig-cap-location: margin
editor: source

